export const metadata = {
  title: 'Full Stack App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <h1>This is the main layout</h1>
        {children}</body>
    </html>
  )
}
